Us 7.1/multiple registration options
RGPosadas/LitterRally pull request #110
Opened 2020-12-05 21:07 UTC by bit172

This PR implements #30.

**Notes**
There is not OAuth e2e as that would be completed in #99. There is also a problem with accessing OAuth provider sites using cypress.

2020-12-06 02:27 UTC, r-saba requested changes
- I can register the same email multiple times using local registration, there should be a check for this.

- There's no verification that I am the owner of the email for local registration. What's the plan for this?

2020-12-06 02:27 UTC, r-saba commented on apps/mull-api/src/app/entities/user.entity.ts
> +import { Field, ID, Int, ObjectType, registerEnumType } from '@nestjs/graphql';
since we don't need `Int` anymore
```suggestion
import { Field, ID, ObjectType, registerEnumType } from '@nestjs/graphql';
```

2020-12-06 02:27 UTC, r-saba commented on apps/mull-api/src/app/user/inputs/user.input.ts
> -  @Field(() => Int)
Remember to remove the `Int` import here and everywhere else using the linter

2020-12-06 02:27 UTC, r-saba commented on apps/mull-ui/src/app/hooks/useToast.tsx
> +export const useToast = () => {
custom hooks, I like it!

2020-12-06 02:27 UTC, r-saba commented on apps/mull-ui/src/app/pages/login/login.scss
> +    outline: none;
unecessary css
```suggestion
```

2020-12-06 02:27 UTC, r-saba commented on apps/mull-ui/src/app/pages/login/login.scss
> +    color: black;
Unnecessary
```suggestion
```

2020-12-06 02:27 UTC, r-saba commented on apps/mull-ui/src/app/pages/login/login.scss
>    grid-template-columns: 1fr;
I haven't used grid too much but this seems unecessary. Double check if remove if it is
```suggestion
```

2020-12-06 02:27 UTC, r-saba commented on apps/mull-ui/src/app/pages/login/login.scss
> +    flex-direction: row;
default flex-direction is row, no need to specify it explicitly. If it's elsewhere please remove from there as well
```suggestion
```

2020-12-06 02:27 UTC, r-saba commented on apps/mull-ui/src/app/pages/login/login.scss
> +    cursor: pointer;
Redundant css we have this style on the button element already
```suggestion
```

2020-12-06 02:27 UTC, r-saba commented on apps/mull-ui/src/app/pages/login/login.scss
> +    margin-bottom: 2rem;
Not sure why this button specifically needs a margin bottom. Seem unnecessary if so please remove.
```suggestion
```

2020-12-06 16:25 UTC, RGPosadas reviewed
I didn't catch anything else that Ragith already caught, so I'll just leave a comment instead of blocking.

The biggest blocker is of course the ability to locally register again with the same email. We should have a toast notification that says something like `User with this email already exists.` as well.

Otherwise, good work! 🚀

2020-12-07 17:05 UTC, RGPosadas requested changes
Thanks for adding in the check to verify if a local email has already been registered or not! 😄 
However, due to that change, the e2e test is now failing as it is trying to register the same user.

2020-12-07 18:09 UTC, RGPosadas reviewed
Thanks for fixing the e2e test!
I'm getting a failing backend unit test now however :/
![image](https://user-images.githubusercontent.com/33991121/101387526-8d2c4e00-388c-11eb-9e07-de3d4047df09.png)

2020-12-08 02:22 UTC, RGPosadas approved these changes, later dismissed
LGTM! 🚀 

**Acceptance Criteria**
- [x] User acceptance flow is respected
- [x] Registration page is implemented
- [x] Documentation present for every new component and function
- [x] Unit and UI tests are implemented for every component and function
- [x] There must exist an automated Cypress acceptance test (I acknowledge that the E2E tests for the OAuth services will be done in #99)
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2079%3A70811)

2020-12-08 23:37 UTC, r-saba approved these changes
LGTM! 🚀 

**Acceptance Criteria**
- [x] User acceptance flow is respected
- [x] Registration page is implemented
- [x] Documentation present for every new component and function
- [x] Unit and UI tests are implemented for every component and function
- [x] There must exist an automated Cypress acceptance test (I acknowledge that the E2E tests for the OAuth services will be done in #99)
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2079%3A70811)

2020-12-09 01:33 UTC, RGPosadas approved these changes

2020-12-09 03:19 UTC, merged