Task 43/event host announcements frontend
RGPosadas/LitterRally pull request #176
Opened 2021-01-26 23:12 UTC by cindyslittleplanet

This PR closes #157. 

You can access the Announcement page by going on http://localhost:4200/messages/announcements.

Notes:
- The Announcement page will also show up on the `Group Chat` tab since the Group Chat page has not been created yet. 
- Even though this is the Announcement page, the CSS for the participant bubble has also been created and shown on the Announcement page for later use in the Group Chat page. 
- Keep in mind that there is currently no way to know if the user is a host or participant, and thus, the use of the boolean `isHost` for now.

2021-01-27 04:31 UTC, JimLau49 requested changes
There seems to be an issue where the announcement text bubble is spilling into the `sub-nav-bar-container`

![image](https://user-images.githubusercontent.com/35787279/105935841-b19cdf00-6020-11eb-8c51-ade609157989.png) 

I played around a bit in the css and if i changed the to `top: 8.55rem` this issue no longer appears for me. Also note my resolution is (2560x1440) if that may be a cause 
![image](https://user-images.githubusercontent.com/35787279/105936373-8b2b7380-6021-11eb-8c95-792c1597fa16.png)


- [x] 43.1 Slider to navigate between group chat and announcements
- [x] 43.2 Announcements bubble shows up on page
- [x] 43.3 Hosts can view a textbox where they can type their announcement
- [x] 43.4 Add hamburger menu icon (but no functionality)  
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every component and function
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2087%3A74417)

2021-01-27 04:31 UTC, JimLau49 commented on apps/mull-ui/src/app/app.tsx
> +                  {/* <Route path={ROUTES.GROUPCHAT} component={GroupChatPage} /> */}
Is this comment a placeholder for the group chat feature? If so i think we should add a TODO comment to explain what it is, I believe there isn't an issue number for this yet so no need to include that

2021-01-27 05:23 UTC, cindyslittleplanet commented on apps/mull-ui/src/app/app.tsx
> +                  {/* <Route path={ROUTES.GROUPCHAT} component={GroupChatPage} /> */}
- Decreased the top to 8.55rem and increased the padding to 0.9rem to get the same spacing
- Added the TODO for the Group Chat placeholder

2021-01-27 14:56 UTC, osahtout commented
Can I ask if it's possible to reduce the width of the green and grey chat bubble (have the chat bubble end right before the other user's profile) and to bring 'group' and 'announcement' a tad bit closer together since it's a little too close to the hamburger menu?


<img width="248" alt="image" src="https://user-images.githubusercontent.com/44760251/106008593-74b70380-6085-11eb-8eec-7a8490cbf4ed.png">

Other than that, it's perfect!

2021-01-27 17:14 UTC, RGPosadas requested changes
**Comments**

1. Swiping works, however `Group Chat` route does not become highlighted (see video). Let me know if this isn't part of your AC, but the way I read it is that subtask 43.1 is supposed to implement this for Group Chat as well.
https://user-images.githubusercontent.com/33991121/106026246-9620eb00-6097-11eb-81f8-2438c5baa1dc.mov

2. I think the upload image button should also have some visual feedback when clicked (like how the other buttons get a grey highlight over them).
https://user-images.githubusercontent.com/33991121/106027559-00865b00-6099-11eb-80f1-beff3124493d.mov



3. Also, got a few linting errors and a failing snapshot on the frontend, so make sure to update those as well 🚀 

**Subtasks**

- [ ] 43.1 Slider to navigate between group chat and announcements
- [x] 43.2 Announcements bubble shows up on page
- [x] 43.3 Hosts can view a textbox where they can type their announcement
- [x] 43.4 Add hamburger menu icon (but no functionality)  

**Acceptance Criteria**

- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every component and function
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2087%3A74417)

2021-01-27 17:14 UTC, RGPosadas commented on apps/mull-ui/src/app/components/chat-bubble/chat-bubble.tsx
> +  isHost?: boolean;
```suggestion
  isCurrentUser?: boolean;
```
Just a small suggestion about the prop name. Technically, everyone commenting on the Announcements page is a host/co-host, so the name of this boolean is not too representative. The chat colour should be green if it the comment is the current-logged-in-user, and them being a host or not isn't really a factor in that.

2021-01-27 17:14 UTC, RGPosadas commented on apps/mull-ui/src/app/components/navigation/sub-nav-bar/sub-nav-bar.tsx
> +  routes: IRoutes[];
Niceee, super clean!

2021-01-27 18:30 UTC, JimLau49 commented on apps/mull-ui/src/app/app.tsx
> +                  {/* <Route path={ROUTES.GROUPCHAT} component={GroupChatPage} /> */}
Thanks for the Quick work

2021-01-27 22:40 UTC, TheGreatMarkus requested changes
Great Work! Looks awesome.

Had some suggestions, nothing major. But I think that they would improve the readability a bit.

2021-01-27 22:40 UTC, cristian-aldea commented on libs/types/src/lib/types.ts
> +export interface IRoutes {
It's an interface defining a route, so:
```suggestion
export interface IRoute {
```

2021-01-27 22:40 UTC, cristian-aldea commented on apps/mull-ui/src/app/components/chat-bubble/chat-bubble.scss
> +.host-chat-container {
This chat bubble is going to use in a bunch of places. The `host-chat-container` tag refers to when a chat bubble is made by the current user (just like on Messenger, when you type bubbles then show on the right like for `host-chat-container`). I think the name should be more generic.

```suggestion
.right-chat-container {
```
or 
```suggestion
.current-user-chat-container {
```

This comment applies to all the places you're using `host` and `participant` in this component so that I don't repeat

2021-01-27 22:40 UTC, cristian-aldea commented on apps/mull-ui/src/app/components/chat-input/chat-input.tsx
> +          </button>
Please set the width/height for this button to be the same, it's currently a bit squished and looks weird.

Before:
![image](https://user-images.githubusercontent.com/23544999/106057696-53263e00-60be-11eb-8dac-61ed363464ad.png)

After:
![image](https://user-images.githubusercontent.com/23544999/106057837-8537a000-60be-11eb-825d-4d397a23291a.png)

2021-01-27 22:40 UTC, cristian-aldea commented on apps/mull-ui/src/app/components/navigation/sub-nav-bar/sub-nav-bar-header.tsx
> +export const SubNavBarHeader = ({ style, className, eventTitle }: SubNavBarHeaderProps) => {
Do you know of maybe a better name for this? This really confused me.

Maybe EventTitleHeader? Or ChatHeader, etc.

2021-01-27 22:40 UTC, cristian-aldea commented on apps/mull-ui/src/app/components/chat-input/chat-input.scss
> +  bottom: 4.75rem;
There is already a var for this. Make this `4.8rem`, which is the height of the bottom nav bar

```suggestion
  bottom: $bot-nav-bar-height-mobile;
```

2021-01-27 22:40 UTC, TheGreatMarkus commented on apps/mull-ui/src/app/components/navigation/sub-nav-bar/sub-nav-bar-header.scss
> +  top: 3.5rem;
There is a variable already available for this value.

See `variables.scss`:
```scss
$top-nav-bar-height-mobile: 3.5rem;
$top-nav-bar-height-desktop: 6.25rem;
```

```suggestion
  top: $top-nav-bar-height-mobile
```

2021-01-27 22:40 UTC, TheGreatMarkus commented on apps/mull-ui/src/app/components/navigation/sub-nav-bar/sub-nav-bar-header.scss
> +    top: 6.25rem;
Same as above
```suggestion
    top: $top-nav-bar-height-desktop
```

2021-01-27 22:40 UTC, TheGreatMarkus commented on apps/mull-ui/src/app/components/navigation/sub-nav-bar/sub-nav-bar.scss
> +    top: 5.75rem;
This value should be `$top-nav-bar-height-mobile` + `$top-nav-header-height-mobile` if I understand correctly. This sub nav bar should be put under those two other components. just like how's its currently done on desktop

2021-01-28 06:33 UTC, cindyslittleplanet commented
@RGPosadas The swiping and highlighting of the Group Chat page will work when the page will be created. See below for an example with a blank page. 
https://user-images.githubusercontent.com/38992971/106099129-2dbe2200-6108-11eb-837b-9411145bd54d.mov
All other issues have been addressed, with the exception of one remaining linting error that needs further discussion to fix.

2021-01-28 16:35 UTC, RGPosadas reviewed
Thanks for addressing my concerns @cindyslittleplanet !

I have one small issue left but I won't block over it. The visual feedback/highlight doesn't highlight over the whole icon, so it looks a bit weird (compare it to the send icon for example)
https://user-images.githubusercontent.com/33991121/106168845-bc5c8e80-615c-11eb-97e9-9c3af0dd0639.mov

2021-01-28 21:05 UTC, JimLau49 approved these changes
Thanks for making my suggested changes and great work 🚀 

- [x] 43.1 Slider to navigate between group chat and announcements
- [x] 43.2 Announcements bubble shows up on page
- [x] 43.3 Hosts can view a textbox where they can type their announcement
- [x] 43.4 Add hamburger menu icon (but no functionality)  
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every component and function
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2087%3A74417)

2021-01-28 23:11 UTC, TheGreatMarkus commented on apps/mull-ui/src/app/components/navigation/sub-nav-bar/sub-nav-bar-header.tsx
> +export const SubNavBarHeader = ({ style, className, eventTitle }: SubNavBarHeaderProps) => {
Perfect, thanks!

2021-01-28 23:14 UTC, TheGreatMarkus approved these changes
All my suggestions were addressed! Sorry for the delay with my review. Great work!

- [x] 43.1 Slider to navigate between group chat and announcements
- [x] 43.2 Announcements bubble shows up on page
- [x] 43.3 Hosts can view a textbox where they can type their announcement
- [x] 43.4 Add hamburger menu icon (but no functionality)  
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every component and function
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2087%3A74417)

2021-01-28 23:56 UTC, RGPosadas approved these changes
Thanks for your hard work! LGTM 🚀 

**Subtasks**

- [x] 43.1 Slider to navigate between group chat and announcements
- [x] 43.2 Announcements bubble shows up on page
- [x] 43.3 Hosts can view a textbox where they can type their announcement
- [x] 43.4 Add hamburger menu icon (but no functionality)  

**Acceptance Criteria**

- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every component and function
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2087%3A74417)

2021-01-29 00:52 UTC, merged