FIX: Convert raw SQL to type ORM syntax
RGPosadas/LitterRally pull request #183
Opened 2021-01-30 03:26 UTC by r-saba

This PR removes technical debt introduced in #154 by converting the raw SQL in `event.service.ts` into typeORM syntax.

Having all our queries use the ORM syntax will make our backend easier to maintain and update as new features are added.

2021-01-31 03:47 UTC, ys-lin reviewed
I ran the tests and there are some test failures...
![image](https://user-images.githubusercontent.com/36641869/106374006-0e640680-634d-11eb-9235-5db3f6036ec6.png)

2021-02-01 03:02 UTC, leojrsilao approved these changes
LGTM! The query looks cleaner now and makes the code more consistent with our other queries. 
🚀 🚀

2021-02-01 23:25 UTC, TheGreatMarkus approved these changes

2021-02-01 23:34 UTC, TheGreatMarkus commented
Oh one thing I would like to mention is that I think you should revert your changes to the snapshot, since it currently doesn't work for everyone as you outlined in #195, no need to change it.

2021-02-01 23:58 UTC, TheGreatMarkus requested changes
Can you first run snapshots tests on my PR #196 and let me know if it passes. If it does, please revert your snapshot changes. If not I'll reapprove

2021-02-02 01:01 UTC, r-saba commented
> Can you first run snapshots tests on my PR #196 and let me know if it passes. If it does, please revert your snapshot changes. If not I'll reapprove

I reverted the snapshot commit.

2021-02-02 01:39 UTC, TheGreatMarkus commented on README.md
> +To test a specific file:
👍

2021-02-02 01:39 UTC, TheGreatMarkus approved these changes

2021-02-02 02:40 UTC, merged