TASK-62: Apply Usability Testing Feedback
RGPosadas/LitterRally pull request #260
Opened 2021-03-11 03:56 UTC by cindyslittleplanet

This PR closes #224.

This PR addresses the issues brought up during usability testing, which includes:

- Events should be sorted by start date
- Create event description input should be a textarea
- Look for a better Event Card "Join" icon
- On desktop, make the Müll logo clickable
- On mobile, create event calendar should not be vertically scrollable

Note: `// @ts-ignore` brings up a linting error, but it can be ignored since this comment is needed to disable the TypeScript type error of `touchDragEnabled`. This is an error from the creator's original component.

2021-03-11 17:32 UTC, RGPosadas requested changes
1. The scroll bar looks awkward since it is on top of the border and cuts it off.
![image](https://user-images.githubusercontent.com/33991121/110827864-7965fe80-8264-11eb-9daf-91d6e63face0.png)

2. EventPage component and the data saved to the database must take in new lines as well. We wanted description to be a textarea so that we could store paragraphs with new lines as the event description, but the current implementation does not do that. This wasn't explicit in the AC so don't worry, but let's fix it now
![image](https://user-images.githubusercontent.com/33991121/110828954-9a7b1f00-8265-11eb-8ef9-92c75bb57a7e.png)

2021-03-11 17:32 UTC, RGPosadas commented on apps/mull-ui/src/app/pages/create-event/create-event.tsx
> +            /> */}
Don't forget to delete this

2021-03-11 17:32 UTC, RGPosadas commented on package-lock.json
> +          "version": "2.0.4",
Make sure to run `npm i` to restore fs-capacitor back to 6.2.0, and graphql-upload back to 11.0.0

2021-03-11 17:34 UTC, RGPosadas commented on apps/mull-ui/src/app/pages/home/discover/discover-page.tsx
> +    const sortedEvents = events
My Events and Upcoming pages should also have sorted events

2021-03-12 06:48 UTC, leojrsilao commented
> 2\. the data saved to the database must take in new lines as well. We wanted description to be a textarea so that we could store paragraphs with new lines as the event description, but the current implementation does not do that. This wasn't explicit in the AC so don't worry, but let's fix it now

Added `white-space: pre-line` attribute for textarea tags or divs tags that need line breaks if a user wants line breaks in them, this will keep the spaces in the paragraphs and won't require to edit the database.

2021-03-12 15:59 UTC, RGPosadas approved these changes
Thanks for quickly applying my feedback. Great work guys!

Approved but please address these before merging (you don't need to ask me to re-review):
* Address my comment about code duplication
* Update the snapshot for profile-header.tsx

Other than that, LGTM! 🚀 

**Subtasks**

- [x] 62.1 Events should be sorted by start date
- [x] 62.2 Create event description input should be a textarea
- [x] 62.3 Look for a better Event Card "Join" icon
- [x] 62.4 On desktop, make the Müll logo clickable
- [x] 62.5 On mobile, create event calendar should not be vertically scrollable

**Acceptance Criteria**

- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every new component and function
- [x] The application should still work with seeded data
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=534%3A6528)

2021-03-12 15:59 UTC, RGPosadas commented on apps/mull-ui/src/app/pages/home/discover/discover-page.tsx
> +    const sortedEvents = events
Since this sorting function is used in three different places, you can add it to `utilities.ts` to avoid code duplication.

2021-03-12 21:18 UTC, ys-lin approved these changes
LGTM 🚀 
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every new component and function
- [x] The application should still work with seeded data
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=534%3A6528)

2021-03-13 02:45 UTC, cristian-aldea approved these changes
Everything looks great! Had some small 💡suggestions.

- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every new component and function
- [x] The application should still work with seeded data
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=534%3A6528)

2021-03-13 02:45 UTC, cristian-aldea commented on apps/mull-ui/src/app/pages/create-event/date-calendar/date-calendar.tsx
> +          touchDragEnabled={false}
💡 mute linting issue (aka tell eslint to shut up about us telling typescript to shut up)

```suggestion
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          // @ts-ignore
          touchDragEnabled={false}
```

2021-03-13 02:45 UTC, cristian-aldea commented on apps/mull-ui/src/app/pages/home/discover/discover-page.tsx
> +import { sortEventsByDate } from 'apps/mull-ui/src/utilities';
💡 Fix linting issue
```suggestion
import { sortEventsByDate } from '../../../../utilities';
```

2021-03-13 02:45 UTC, cristian-aldea commented on apps/mull-ui/src/app/pages/home/my-events/my-events.tsx
> +import { sortEventsByDate } from 'apps/mull-ui/src/utilities';
💡 fix lint issue
```suggestion
import { sortEventsByDate } from '../../../../utilities';
```

2021-03-13 02:45 UTC, cristian-aldea commented on apps/mull-ui/src/app/pages/home/upcoming/upcoming.tsx
> +import { sortEventsByDate } from 'apps/mull-ui/src/utilities';
💡 fix lint issue
```suggestion
import { sortEventsByDate } from '../../../../utilities';
```

2021-03-13 02:45 UTC, cristian-aldea commented on apps/mull-ui/src/app/pages/create-event/create-event.tsx
> +            </div>
💡Just a note but this could be turned into a component if it ends up being used in multiple places, like for the edit profile page for example

2021-03-13 02:45 UTC, cristian-aldea commented on apps/mull-ui/src/app/pages/create-event/create-event.scss
> +.textarea-create-event-container {
💡 General suggestions for the changes made in this file
* use variables for colours in case they are useful elsewhere
* use rem over px

2021-03-13 03:24 UTC, merged