TASK-44: Add cancel button in my events page
RGPosadas/LitterRally pull request #292
Opened 2021-03-19 20:13 UTC by leojrsilao

This PR closes #162.

To test this PR:
Go to the my events tab and click on cancel event.

2021-03-20 15:31 UTC, JimLau49 requested changes
Nice work but I have some changes,

Firstly, the X button doesn't seem to be aligned for me. This may be because my resolution scaling of my monitor is not 16:9
![image](https://user-images.githubusercontent.com/35787279/111874990-d309af80-896d-11eb-91d8-0b7214a7aa67.png)

Additionally there also seems to be overflow caused by the X button positioning which is leading to a scrollbar appearing in the modal 

![image](https://user-images.githubusercontent.com/35787279/111875089-56c39c00-896e-11eb-8549-4b0ea0e8c232.png)

I'll leave some suggestions as to how to fix this below

2021-03-20 15:31 UTC, JimLau49 commented on apps/mull-ui/src/app/pages/event-page/event-page-info/event-page-info.scss
> +}
```suggestion
.cancel-modal-container {
  position: relative;
  display: flex;
  flex-direction: column;
  justify-content: center;
  overflow:hidden;
  .cancel-event-title {
    align-self: center;
  }
  .close-button {
    position: absolute;
    bottom: 21.75rem;
    left: 12.15rem;
    cursor: pointer;
  }
}
```

![image](https://user-images.githubusercontent.com/35787279/111875152-b0c46180-896e-11eb-8381-cadb931bedcf.png)

2021-03-20 18:16 UTC, JimLau49 approved these changes
🚀
**Acceptance Criteria**

- [x] Mull button should show "cancel" for events I created
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every component and function
- [x] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2079%3A74708)

2021-03-21 23:11 UTC, osahtout approved these changes
- [X] Does match the mockup that I don't remember making
- It's nice that there's no functionality because I think we need to discuss as a team what happens when cancelling an event

2021-03-22 02:04 UTC, merged