Task-89: Event Page Review/Preview Styling/US Cleanup
RGPosadas/LitterRally pull request #331
Opened 2021-04-03 03:53 UTC by osahtout

closes #317 

Second cleanup pr

2021-04-04 21:36 UTC, RGPosadas approved these changes
LGTM 🚀 

- [x] 89.1 Comment out unused SVG icons (messages + map)
- [x] 89.2 Comment out "Invite Friend" row
- [x] 89.3 Host’s avatar should be shown
- [x] 89.4 On Preview: should highlight Home button

2021-04-05 00:45 UTC, r-saba requested changes

2021-04-05 00:45 UTC, r-saba commented on apps/mull-ui/src/app/pages/event-page/event-page-info/event-page-info.tsx
> +        <img src={avatarUrl(event.host as User)} className="event-page-icon" alt="Event"></img>
This is a rectangle for me. Can you make it circular like the other user-profile images. You will need to add the following styling to this element

```
border-radius: 50%;
object-fit: cover;
```

2021-04-05 03:46 UTC, r-saba approved these changes
LGTM! 

- [x] 89.1 Comment out unused SVG icons (messages + map)
- [x] 89.2 Comment out "Invite Friend" row
- [x] 89.3 Host’s avatar should be shown
- [x] 89.4 On Preview: should highlight Home button

2021-04-05 03:47 UTC, merged