Task 90/event card styling/ux cleanup
RGPosadas/LitterRally pull request #347
Opened 2021-04-07 18:26 UTC by osahtout

closes #318 

No participants:
![Screenshot 2021-04-07 140305](https://user-images.githubusercontent.com/44760251/113915137-67687480-97ac-11eb-84ab-6b162a5fbf29.png)

One Participant:
![Screenshot 2021-04-07 140320](https://user-images.githubusercontent.com/44760251/113915196-77805400-97ac-11eb-9af9-e253fdffad06.png)

Two participants:
![Screenshot 2021-04-07 140338](https://user-images.githubusercontent.com/44760251/113915220-7e0ecb80-97ac-11eb-909e-8b42ec5052c1.png)

Three or more participants:
![Screenshot 2021-04-07 140354](https://user-images.githubusercontent.com/44760251/113915247-89fa8d80-97ac-11eb-9029-317237fba4a7.png)

Will randomly query three participants so the avatars will be different all the time.

Oh and removed the border and added box shadow
![image](https://user-images.githubusercontent.com/44760251/113915750-24f36780-97ad-11eb-9f09-c6aad743f267.png)

2021-04-07 20:14 UTC, leojrsilao requested changes
Noticed that in front end, the snapshots aren't updated, and in backend, 1 test fails. 

Other than that LGTM!

2021-04-08 00:14 UTC, leojrsilao approved these changes

2021-04-08 01:54 UTC, ys-lin approved these changes
- [x] Documentation present where necessary
- [x] Unit and UI tests are implemented for every new component and function
- [x] The application should still work with seeded data

2021-04-08 02:02 UTC, cristian-aldea approved these changes

2021-04-08 02:07 UTC, merged