Fix test to remove error messages on travis
RGPosadas/LitterRally pull request #85
Opened 2020-11-17 23:19 UTC by JimLau49

This Fix aims to fix the error messages we're getting on travis about synthetic events
`     Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property bubbles on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.`

2020-11-17 23:36 UTC, TheGreatMarkus requested changes
Looks good! Just remember to update the snapshots

2020-11-18 00:26 UTC, TheGreatMarkus commented
Just clarifying that these errors appear when running tests on ui-lib

2020-11-18 02:01 UTC, RGPosadas approved these changes
Thanks Jimmy, this ended up clearing about ~150 lines on the Travis logs!
LGTM 🚀

2020-11-18 02:04 UTC, TheGreatMarkus approved these changes

2020-11-18 02:05 UTC, merged